include:
  - project: 'quiqqer/stabilization/semantic-release'
    file: '/ci-templates/.gitlab-ci.yml'

variables:
  PACKAGE_NAME: "quiqqer/quiqqer"

phpunit:
  image: pcsgjan/quiqqer:dev
  stage: test
  before_script:
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - cd /var/www
  script:
    - ./console composer config repositories.local path ${CI_PROJECT_DIR}
    - COMPOSER_MIRROR_PATH_REPOS=1 ./console composer require ${PACKAGE_NAME}:@dev
    - cd packages/${PACKAGE_NAME}
    - curl -sSL --output /tmp/phpunit.phar "https://phar.phpunit.de/phpunit-10.phar"
    - chmod +x /tmp/phpunit.phar
    - /tmp/phpunit
