include:
  - project: 'quiqqer/stabilization/semantic-release'
    file: '/ci-templates/.gitlab-ci.yml'

variables:
  PACKAGE_NAME: "quiqqer/quiqqer"

phpunit:
  image: quiqqer/testing:dev
  stage: test
  before_script:
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    - git -C ${CI_PROJECT_DIR} fetch origin ${CI_DEFAULT_BRANCH}
    - QUIQQER_LATEST_RELEASE=`git -C ${CI_PROJECT_DIR} describe --tags --abbrev=0 ${CI_DEFAULT_BRANCH}`
    - cd /var/www/html
  script:
    - ./console composer config repositories.local path ${CI_PROJECT_DIR}
    - COMPOSER_MIRROR_PATH_REPOS=1 ./console composer require ${PACKAGE_NAME}:"dev-${CI_COMMIT_SHA}@dev as ${QUIQQER_LATEST_RELEASE}"
    - cd packages/${PACKAGE_NAME}
    - curl -sSL --output /tmp/phpunit.phar "https://phar.phpunit.de/phpunit-10.phar"
    - chmod +x /tmp/phpunit.phar
    - /tmp/phpunit.phar
